apiVersion: v1
kind: Service
metadata:
  name: frankdb
  labels:
    app: frankdb
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: frankdb
---
apiVersion: v1
kind: Service
metadata:
  name: frankthecloud
  labels:
    app: frankthecloud
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: frankthecloud
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frankdb
spec:
  selector:
    matchLabels:
      app: frankdb
  replicas: 1
  template:
    metadata:
      labels:
        app: frankdb
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: frankdb
          imagePullPolicy: Always
          image: seantywork/frankdb
          ports:
          - containerPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frankthecloud
spec:
  selector:
    matchLabels:
      app: frankthecloud
  replicas: 1
  template:
    metadata:
      labels:
        app: frankthecloud
    spec:
      imagePullSecrets:
      - name: docker-secret
      containers:
      - name: frankthecloud
        imagePullPolicy: Always
        image: seantywork/frankthecloud
        ports:
        - containerPort: 8000