name: frank the cloud self hosted runner

on :
  push:
    branches: [ main ]

jobs:

  frank_the_cloud_self_hosted_build:
    runs-on: self-hosted
    steps: 
      - run: mkdir -p /root/frank
      - run: git -C /root/frank init
      - run: git -C /root/frank pull https://github.com/seantywork/frank-the-cloud.git 
      - run: docker-compose -f /root/frank/docker-compose.yaml up -d --build
      - run: docker-compose -f /root/frank/docker-compose.yaml down
      - run: docker tag frank_frankdb seantywork/frankdb
      - run: docker tag frank_frankthecloud seantywork/frankthecloud
      - run: docker push seantywork/frankdb
      - run: docker push seantywork/frankthecloud
      - run: rm -r /root/frank

  frank_the_cloud_self_hosted_deployment:
    needs: frank_the_cloud_self_hosted_build
    runs-on: self-hosted
    steps:

      - run: ssh $SSH_XY "kubectl -n frank rollout restart deployment/frankthecloud"

 
