apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: sorrylinus-again-pv
spec: 
  capacity: 
    storage: 16Gi 
  volumeMode: Filesystem 
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs 
  mountOptions: 
    - hard 
    - nfsvers=4.1 
  nfs: 
    path: /data/sorrylinus-again 
    server: 192.168.0.32

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sorrylinus-again-pvc
spec:
  storageClassName: nfs-default-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi