#!/bin/bash
function usage_helper(){

    echo "usage:"
    echo "  again : build sorrylinus again only"
    echo "  hub   : build sorrylinus hub only"
    echo "  soli  : build both" 
    echo "  test  : for test "
}

function build_sorrylinus_again(){

    echo "======BUILD SORRYLINUS AGAIN START======"

    SRC_OJSON="${SOLI_AGAIN_DEV_DIR}/${SOLI_AGAIN_OAUTH_JSON}"
    SRC_CYAML="${SOLI_AGAIN_DEV_DIR}/${SOLI_AGAIN_CONFIG_YAML}"

    DST_OJSON="${SOLI_AGAIN_PROD_DIR}/${SOLI_AGAIN_OAUTH_JSON}"
    DST_CYAML="${SOLI_AGAIN_PROD_DIR}/${SOLI_AGAIN_CONFIG_YAML}"

    /bin/cp -Rf "${SRC_OJSON}" "${DST_OJSON}"
    /bin/cp -Rf "${SRC_CYAML}" "${DST_CYAML}"

    isDebugOn=$(cat file.txt | grep -c "debug: true")

    if [ $isDebugOn -eq 1 ]
    then
        echo "sorrylinus-again: check debug flag"
        exit 1
    fi

    pushd "${SOLI_AGAIN_PROD_DIR}"

    git pull

    sudo docker compose -f docker-compose.yaml.build up --build -d

    sudo docker compose -f docker-compose.yaml.build down

    sudo docker tag sorrylinus-again-sorrylinus-again "${SOLI_AGAIN_IMG_ADDR}"

    sudo docker push "${SOLI_AGAIN_IMG_ADDR}"

    popd

    echo "======BUILD SORRYLINUS AGAIN END======"

}


function build_sorrylinus_hub(){

    echo "======BUILD SORRYLINUS HUB START======"

    pushd "${SOLI_HUB_PROD_DIR}"

    git pull

    sudo docker compose -f docker-compose.yaml.build up --build -d

    sudo docker compose -f docker-compose.yaml.build down 

    sudo docker tag hub-sorrylinus-hub "${SOLI_HUB_IMG_ADDR}"

    sudo docker push "${SOLI_HUB_IMG_ADDR}"

    popd

    echo "======BUILD SORRYLINUS HUB END======"

}


function deploy_sorrylinus_again(){

    echo "======DEPLOY SORRYLINUS AGAIN START======"

    EXEC_DEPLOY="${SSHX} '${SSHY} ${SOLI_AGAIN_DEPLOY_CMD}'"

    /bin/bash -c "${EXEC_DEPLOY}"

    echo "======DEPLOY SORRYLINUS AGAIN END======"

}


function deploy_sorrylinus_hub(){

    echo "======DEPLOY SORRYLINUS HUB START======"

    EXEC_DEPLOY="${SSHX} '${SSHY} ${SOLI_HUB_DEPLOY_CMD}'"

    /bin/bash -c "${EXEC_DEPLOY}"

    echo "======DEPLOY SORRYLINUS HUB END======"
}


function test_part(){

    echo "add whatever you want"
}

if [ ! -f "./cicd.conf" ]
then
    echo "cicd.conf not found"
    exit 1
fi



if [ -z "$1" ]
then 

    echo "argument is empty"

    usage_helper
    
    exit 1
fi

source ./cicd.conf


if [ "$1" == "again" ]
then 

    build_sorrylinus_again

    deploy_sorrylinus_again


elif [ "$1" == "hub" ]
then 

    build_sorrylinus_hub

    deploy_sorrylinus_hub

elif [ "$1" == "soli" ]
then 

    build_sorrylinus_again

    build_sorrylinus_hub

    deploy_sorrylinus_again

    deploy_sorrylinus_hub

elif [ "$1" == "test" ]
then 

    test_part

else 

    echo "wrong argument: $1"

    usage_helper

    exit 1

fi

echo "finished running cicd pipeline"



