#!/bin/bash

echo "root generating...."

openssl genrsa -out ./tls_bin/ca/ca_priv.pem 4096

openssl rsa -in ./tls_bin/ca/ca_priv.pem -outform PEM -pubout -out ./tls_bin/ca/ca_pub.pem

openssl req -x509 -new -key ./tls_bin/ca/ca_priv.pem -days 3650 -out ./tls_bin/ca/ca.crt -subj "/CN=issuerforseantywork"

echo "hub key pair, csr generating...."

openssl genrsa -out ./tls_bin/hub/sub_priv.pem 4096

openssl rsa -in ./tls_bin/hub/sub_priv.pem -outform PEM -pubout -out ./tls_bin/hub/sub_pub.pem

openssl req -key ./tls_bin/hub/sub_priv.pem -new -sha256 -out ./tls_bin/hub/sub.csr  -subj "/CN=subjectforseantywork"

echo "sock key pair, csr generating...."

openssl genrsa -out ./tls_bin/sock/sub_client_priv.pem 4096

openssl rsa -in ./tls_bin/sock/sub_client_priv.pem -outform PEM -pubout -out ./tls_bin/sock/sub_client_pub.pem

openssl req -key ./tls_bin/sock/sub_client_priv.pem -new -sha256 -out ./tls_bin/sock/sub_client.csr  -subj "/CN=subjectclientforseantywork"

echo "signing requests for hub, sock...."

openssl  x509 -req -days 365 -in ./tls_bin/hub/sub.csr -CA ./tls_bin/ca/ca.crt -CAkey ./tls_bin/ca/ca_priv.pem -CAcreateserial -sha256 -out ./tls_bin/hub/sub.crt

openssl  x509 -req -days 365 -in ./tls_bin/sock/sub_client.csr -CA ./tls_bin/ca/ca.crt -CAkey ./tls_bin/ca/ca_priv.pem -CAcreateserial -sha256 -out ./tls_bin/sock/sub_client.crt

echo "done!"
