version: "3"

services:


        frankhub:
                build: ./hub
                container_name: frankhub
                ports:  
                        - "3000:3000"
                        - "3001:3001"
                tty: true
                restart: always

